WebShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class ProductController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        /// <summary>
        /// User Section
        /// </summary>
        #region User Section
        // GET: ProductModels
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        // GET: ProductModels/Index
        [HttpGet]
        public PartialViewResult Index_Partial(int selectedPage = 0, int elementsPerPage = 5, int selectedCategory = 0, int selectedSubcategory = 0, int price = Int32.MaxValue)
        {
            List<ProductModels> products = db.ProductModel.Where(x => x.SubcategoryModelsId == selectedSubcategory).ToList();

            for (int i = 0; i < products.Count; i++)
                if (products[i].Description != null && products[i].Description.Length > 40)
                {
                    products[i].Description = products[i].Description.Substring(0, 40) + "...";
                }

            //Get all categories and selected category
            ViewBag.categories = db.CategoryModel.ToList();
            ViewBag.selectedCategory = selectedCategory;

            //Get all subcategories and selected subcategory
            ViewBag.subcategories = db.SubcategoryModel.Where(x => x.CategoryModelsId == selectedCategory).ToList();
            ViewBag.selectedSubcategory = selectedSubcategory;

            ViewBag.numberOfPages = Math.Ceiling((double)products.Count / elementsPerPage);
            ViewBag.selectedPage = selectedPage;
            ViewBag.elementsPerPage = elementsPerPage;
            ViewBag.price = price;

            //Apply all search criteria
            products = products.Where(x => x.Price <= price)
                               .OrderBy(x => x.Id)
                               .Skip(selectedPage * elementsPerPage)
                               .Take(elementsPerPage)
                               .ToList();

            return PartialView(products);
        }

        // GET: ProductModels/Details/5
        [HttpGet]
        public ActionResult Details(int id)
        {
            ProductModels productModels = db.ProductModel.Where(x => x.Id == id).FirstOrDefault();
            List<ReviewModels> reviews = db.ReviewModels.Include(x => x.UserModel).Where(x => x.ProductModelId == id).OrderByDescending(x => x.Created_At).ToList();

            double rating = 0;

            if (productModels == null)
            {
                return HttpNotFound();
            }

            foreach (var item in reviews)
                rating += item.Rating;

            rating = rating / reviews.Count + 0.5;

            productModels.Rating = (int)rating;
            productModels.Reviews = reviews;

            return View(productModels);
        }
        #endregion

        /// <summary>
        /// Admin Section
        /// </summary>
        #region Admin Section
        // GET: ProductModels/Index
        [HttpGet]
        [ApplicationAuthorize]
        public ActionResult Admin_Product_Index()
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                return PartialView("Admin_Index_Partial", db.ProductModel.Include(x => x.SubcategoryModels).ToList());

            return Redirect("/Admin/Index");
        }

        [HttpGet]
        [ApplicationAuthorize]
        public ActionResult Admin_Product_Details(int productId)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                return PartialView("Admin_Details_Partial", db.ProductModel.Include(x => x.SubcategoryModels)
                                                                           .Include(x => x.Reviews)
                                                                           .Include("Reviews.UserModel")
                                                                           .Where(x => x.Id == productId)
                                                                           .FirstOrDefault());

            return Redirect("/Admin/Index");
        }

        // GET: ProductModels/Create
        [HttpGet]
        [ApplicationAuthorize]
        public ActionResult Admin_Product_Create()
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                List<SelectListItem> subcategories = db.SubcategoryModel.Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToList();

                ViewBag.subcategories = subcategories;

                return PartialView("Admin_Create_Partial");
            }

            return Redirect("/Admin/Index");
        }

        // POST: ProductModels/Create
        [HttpPost]
        [ApplicationAuthorize]
        public ActionResult Admin_Product_Create(ProductModels productModels)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                List<string> allErrors = new List<string>();

                if (productModels.Name == null || productModels.Name == String.Empty)
                    allErrors.Add("Name is required!");
                if (productModels.Price == 0)
                    allErrors.Add("Price is required!");

                if (allErrors.Count > 0)
                    return Json(new {statusCode = 400, success = false, responseMessage = allErrors });

                productModels.Created_At = DateTime.Now;
                productModels.Updated_At = DateTime.Now;
                productModels.Rating = 0;
                db.ProductModel.Add(productModels);
                db.SaveChanges();
                return Json(new {statusCode = 200, success = true, responseMessage = "Product Added!" });
            }

            return Json(new { statusCode = 401 });
        }

        // GET: ProductModels/Edit
        [HttpGet]
        [ApplicationAuthorize]
        public ActionResult Admin_Product_Edit(int productId)
        {
            var product = db.ProductModel.Find(productId);

            if (product == null)
                return HttpNotFound();

            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                List<SelectListItem> subcategories = db.SubcategoryModel.Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString(),
                    Selected = product.SubcategoryModelsId == x.Id?true:false
                }).ToList();

                ViewBag.subcategories = subcategories;

                return PartialView("Admin_Edit_Partial",product);
            }

            return Redirect("/Admin/Index");
        }

        // PUT: ProductModels/Edit
        [HttpPost]
        [ApplicationAuthorize]
        public ActionResult Admin_Product_Edit(ProductModels productModel)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                List<string> allErrors = new List<string>();

                if (productModel.Name == null || productModel.Name == String.Empty)
                    allErrors.Add("Name is required!");
                if (productModel.Price == 0)
                    allErrors.Add("Price is required!");

                if (allErrors.Count > 0)
                    return Json(new { statusCode = 400, success = false, responseMessage = allErrors });

                var product = db.ProductModel.Find(productModel.Id);
                product.ImagePath = productModel.ImagePath != null ? productModel.ImagePath : product.ImagePath;
                product.Name = productModel.Name != null && productModel.Name != String.Empty ? productModel.Name : product.Name;
                product.Price = productModel.Price != 0 ? productModel.Price : product.Price;
                product.SubcategoryModelsId = productModel.SubcategoryModelsId != 0 ? productModel.SubcategoryModelsId : product.SubcategoryModelsId;
                product.Updated_At = DateTime.Now;

                db.SaveChanges();
                return Json(new { statusCode = 200, success = true, responseMessage = "Product Edited!" });
            }

            return Json(new { statusCode = 401 });
        }

        // DELETE: ProductModels/Delete
        [HttpPost]
        [ApplicationAuthorize]
        public ActionResult Admin_Product_Delete(int productId)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                db.ProductModel.Remove(db.ProductModel.Find(productId));
                db.SaveChanges();
                return Json(new { statusCode = 200, success = true, responseMessage = "Product Deleted!" });
            }

            return Json(new { statusCode = 401 });
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebShop/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;
using Microsoft.AspNet.Identity;

namespace WebShop.Controllers
{
    public class ReviewController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // POST: Review/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    // TODO: Add insert logic here
                    ReviewModels review = new ReviewModels();

                    review.ProductModelId = Int32.Parse(collection["productId"]);
                    if (review.ProductModelId == 0)
                    {
                        return Json(new { success = false, responseText = "You are not reviewing any product!" });
                    }

                    review.Description = collection["comment"];
                    if (review.Description == String.Empty)
                    {
                        return Json(new { success = false, responseText = "You have to add a description in order to finish review!" });
                    }

                    int rating;
                    Int32.TryParse(collection["selectedStar"],out rating);
                    review.Rating = rating;
                    if (review.Rating == 0)
                    {
                        return Json(new { success = false, responseText = "You have to rate the product in order to finish review!" });
                    }

                    review.Created_At = DateTime.Now;
                    review.UserModelId = User.Identity.GetUserId();

                    db.ReviewModels.Add(review);
                    db.SaveChanges();
                    return Json(new {success = true});
                }
                else
                {
                    return Json(new {success = false,responseText = "You are not loged in so you cant review the product!" });
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Review/Edit/5
        [HttpGet]
        public ActionResult Admin_Review_Edit(int reviewId)
        {
            return PartialView(db.ReviewModels.Find(reviewId));
        }

        // POST: Review/Edit/5
        [HttpPost]
        public ActionResult Admin_Review_Edit(ReviewModels reviewModel)
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    ReviewModels review = db.ReviewModels.Find(reviewModel.Id);

                    if (review == null)
                        return Json(new { statusCode = 404, success = false, responseMessage = "Not found!" });

                    List<string> allErrors = new List<string>();

                    if (reviewModel.Description == null || reviewModel.Description == String.Empty)
                        allErrors.Add("Description is required!");
                    if (allErrors.Count > 0)
                        return Json(new { statusCode = 400, success = false, responseMessage = allErrors });

                    review.Description = reviewModel.Description;
                    review.Rating = reviewModel.Rating;
                    db.SaveChanges();

                    return Json(new { statusCode = 200, success = true, responseMessage = "Review Edited!" });
                }

                return Json(new { statusCode = 401, success = false, responseMessage = "Unauthorized!" });
            }
            catch
            {
                return View();
            }
        }

        // POST: Review/Delete/5
        [HttpPost]
        public ActionResult Admin_Review_Delete(int reviewId)
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    ReviewModels review = db.ReviewModels.Find(reviewId);

                    if (review == null)
                        return Json(new { statusCode = 404, success = false, responseMessage = "Not found!" });

                    db.ReviewModels.Remove(review);
                    db.SaveChanges();

                    return Json(new { statusCode = 200, success = true, responseMessage = "Review Deleted!" });
                }

                return Json(new { statusCode = 401, success = false, responseMessage = "Unaothorized!" });
            }
            catch
            {
                return View();
            }
        }
    }
}

WebShop/Views/Product/Admin_Create_Partial.cshtml
@model WebShop.Models.ProductModels

@{
    var subcategories = (List<SelectListItem>)ViewBag.subcategories;
}

<div id="errorContainer" class="alert alert-danger hidden">

</div>

<div class="form-horizontal">

    <div class="form-group">
        <div class="col-md-12">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" , @placeholder = "Product Name" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.Description, 4, 10, new { @class = "form-control", @placeholder = "Product Description" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control", @placeholder = "Product Image" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @placeholder = "Product Price" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            @Html.DropDownListFor(x => x.SubcategoryModelsId, subcategories, new { @class = "form-control", @placeholder = "Product Subcategory" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Create" class="btn btn-primary" onclick="addNewProduct();"/>
        </div>
    </div>
</div>

WebShop/Views/Product/Admin_Details_Partial.cshtml
@model WebShop.Models.ProductModels

<style>
    .alignRight {
        text-align: right;
    }
</style>

<div class="row">
    @*Product details*@
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading" style="text-align:right">
                <a class="editDeleteDetailsButton" style="" href="#" data-toggle="modal" data-target="#editProductModal"><i class="fa fa-edit" style="color:#387738;"></i></a>
                <a class="editDeleteDetailsButton" style="" href="#" onclick="deleteProduct(@Model.Id);"><i class="fa fa-trash" style="color:#c74646;"></i></a>
            </div>
            <div class="panel-body">
                @Html.HiddenFor(x => x.Id)
                <div class="row">
                    <div class="col-md-6 alignRight"><label>Product Name:</label></div>
                    <div class="col-md-6"><span>@Model.Name</span></div>
                </div>
                <div class="row">
                    <div class="col-md-6 alignRight"><label>Product Description:</label></div>
                    <div class="col-md-6"><span>@Model.Description</span></div>
                </div>
                <div class="row">
                    <div class="col-md-6 alignRight"><label>Product Price:</label></div>
                    <div class="col-md-6"><span>@Model.Price</span></div>
                </div>
                <div class="row">
                    <div class="col-md-6 alignRight"><label>Created:</label></div>
                    <div class="col-md-6"><span>@Model.Created_At</span></div>
                </div>
                <div class="row">
                    <div class="col-md-6 alignRight"><label>Updated:</label></div>
                    <div class="col-md-6"><span>@Model.Updated_At</span></div>
                </div>
            </div>
        </div>
    </div>

    @*Product review details*@
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">Product Reviews(@Model.Reviews.Count)</div>
            <div class="panel-body">
                <div style="overflow-x:auto">
                    <table class="table table-striped">
                        <thead class="thead-inverse">
                            <tr>
                                <th>
                                    User
                                </th>
                                <th>
                                    Description
                                </th>
                                <th>
                                    Rating
                                </th>
                                <th>
                                    Created_At
                                </th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var review in Model.Reviews)
                            {
                                <tr>
                                    <th>
                                        @Html.DisplayFor(modelItem => review.UserModel.UserName)
                                    </th>
                                    <th>
                                        @Html.DisplayFor(modelItem => review.Description)
                                    </th>
                                    <th>
                                        @Html.DisplayFor(modelItem => review.Rating)
                                    </th>
                                    <th>
                                        @review.Created_At.ToString("dd-MM-yyyy HH:mm")
                                    </th>
                                    <th style="position:relative;">
                                        <div id="actionButtons">
                                            <a href="#" class="editDeleteDetailsButton" onclick="" data-toggle="modal" data-target="#editReviewModal_@review.Id"><i class="fa fa-edit" style="color:#387738;"></i></a>
                                            <a href="#" class="editDeleteDetailsButton" value="button" onclick="deleteReview(@review.Id)"><i class="fa fa-trash" style="color:#c74646;"></i></a>
                                        </div>
                                        <!-- Review Modal -->
                                        <div class="modal fade" id="editReviewModal_@review.Id" tabindex="-1" role="dialog" aria-labelledby="editReview" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h3 class="modal-title text-center">Edit Review</h3>
                                                    </div>
                                                    <div class="modal-body">
                                                        @Html.Action("Admin_Review_Edit", "Review", new { reviewId = review.Id })
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </th>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="editProductModal" tabindex="-1" role="dialog" aria-labelledby="addProduct" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-center" id="exampleModalLabel">Edit Product</h3>
            </div>
            <div class="modal-body">
                @Html.Action("Admin_Product_Edit", "Product", new { productId = Model.Id })
            </div>
        </div>
    </div>
</div>

WebShop/Views/Product/Admin_Edit_Partial.cshtml
@model WebShop.Models.ProductModels

@{
    var subcategories = (List<SelectListItem>)ViewBag.subcategories;
}

<div id="errorContainer" class="alert alert-danger hidden">

</div>

<div class="form-horizontal">
    @Html.HiddenFor(x => x.Id)

    <div class="form-group">
        <div class="col-md-12">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Product Name" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.Description, 4, 10, new { @class = "form-control", @placeholder = "Product Description" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control", @placeholder = "Product Image" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @placeholder = "Product Price" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            @Html.DropDownListFor(x => x.SubcategoryModelsId, subcategories, new { @class = "form-control", @placeholder = "Product Subcategory" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Edit" class="btn btn-primary" onclick="editProduct();" />
        </div>
    </div>
</div>

WebShop/Views/Product/Admin_Index_Partial.cshtml
@model IEnumerable<WebShop.Models.ProductModels>

<div class="panel">

    <p class="panel-heading">
        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#addNewProductModal">Add New</a>
    </p>

    <div style="overflow-x:auto" class="panel-body">
        <table class="table table-striped">
            <thead class="thead-inverse">
                <tr>
                    <th>
                        Subcategory
                    </th>
                    <th>
                        Product
                    </th>
                    <th>
                        Image
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        Created_At
                    </th>
                    <th>
                        Updated_At
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th>
                            @Html.DisplayFor(modelItem => item.SubcategoryModels.Name)
                        </th>
                        <th>
                            @Html.DisplayFor(modelItem => item.Name)
                        </th>
                        <th>
                            <img src="@item.ImagePath" alt="Alternate Text" height="30" width="30" />
                        </th>
                        <th>
                            @Html.DisplayFor(modelItem => item.Price)
                        </th>
                        <th>
                            @item.Created_At.ToString("dd-MM-yyyy HH:mm")
                        </th>
                        <th>
                            @item.Updated_At.ToString("dd-MM-yyyy HH:mm")
                        </th>
                        <th style="position:relative;">
                            <div id="actionButtons">
                                <a href="#" class="editDeleteDetailsButton" onclick="getDetails(@item.Id);"><i class="fa fa-info-circle" style="color:#3394ce;"></i></a>
                                <a href="#" class="editDeleteDetailsButton" value="button" onclick="deleteProduct(@item.Id);"><i class="fa fa-trash" style="color:#c74646;"></i></a>
                            </div>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addNewProductModal" tabindex="-1" role="dialog" aria-labelledby="addProduct" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-center">Add New Product</h3>
            </div>
            <div class="modal-body">
                @Html.Action("Admin_Product_Create", "Product")
            </div>
        </div>
    </div>
</div>

WebShop/Views/Product/Delete.cshtml
@model WebShop.Models.ProductModels

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductModels</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebShop/Views/Product/Edit.cshtml
@model WebShop.Models.ProductModels

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebShop/Views/Product/Index.cshtml
@model IEnumerable<WebShop.Models.ProductModels>

@{
    ViewBag.Title = "Index";
}

<link href="~/Content/Sidebar-filters.css" rel="stylesheet" />
<link href="~/Content/Custome-box-container.css" rel="stylesheet" />

<div id="ajaxContainer" style="margin-top:150px">
    @Html.Action("Index_Partial", "Product", new { selectedPage = 0, elementsPerPage = 5 })
</div>