WebShop/Controllers/SubcategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class SubcategoryController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        // GET: Subcategory
        [HttpGet]
        public ActionResult Admin_Subcategory_Index()
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    return PartialView(db.SubcategoryModel.Include("CategoryModels").ToList());

                return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: Subcategory/Create
        [HttpGet]
        public ActionResult Admin_Subcategory_Create()
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin")) { 
                    ViewBag.categories = db.CategoryModel.ToList();
                    return PartialView();
                }

                return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // POST: Subcategory/Create
        [HttpPost]
        public ActionResult Admin_Subcategory_Create(SubcategoryModels subcategoryModel)
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    List<string> allErrors = new List<string>();

                    if (subcategoryModel.Name == null || subcategoryModel.Name == String.Empty)
                        allErrors.Add("Name is required!");
                    if (subcategoryModel.CategoryModelsId == null)
                        allErrors.Add("Category is required!");

                    if (allErrors.Count > 0)
                        return Json(new { statusCode = 400, success = false, responseMessage = allErrors });

                    db.SubcategoryModel.Add(subcategoryModel);
                    db.SaveChanges();

                    return Json(new { statusCode = 200, success = true, responseMessage = "Subcategory Added!" });
                }

                return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: Subcategory/Edit/5
        [HttpGet]
        public ActionResult Admin_Subcategory_Edit(int subcategoryId)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                SubcategoryModels subcategory = db.SubcategoryModel.Find(subcategoryId);

                if (subcategory == null)
                    return Json(new { statusCode = 404, success = false, responseMessage = "Not found!" });

                return PartialView(subcategory);
            }

            return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
        }

        // POST: Subcategory/Edit/5
        [HttpPost]
        public ActionResult Admin_Subcategory_Edit(SubcategoryModels subcategoryModel)
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    SubcategoryModels subcategory = db.SubcategoryModel.Find(subcategoryModel.Id);

                    if (subcategory == null)
                        return Json(new { statusCode = 404, success = false, responseMessage = "Not found!" });

                    List<string> allErrors = new List<string>();

                    if (subcategoryModel.Name == null || subcategoryModel.Name == String.Empty)
                        allErrors.Add("Name is required!");
                    if (subcategoryModel.CategoryModelsId == null)
                        allErrors.Add("Category is required!");

                    if (allErrors.Count > 0)
                        return Json(new { statusCode = 400, success = false, responseMessage = allErrors });

                    subcategory.Name = subcategory.Name;
                    db.SaveChanges();

                    return Json(new { statusCode = 200, success = true, responseMessage = "Category Edited!" });
                }

                return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // POST: Subcategory/Delete/5
        [HttpPost]
        public ActionResult Admin_Subcategory_Delete(int subcategoryId)
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    SubcategoryModels subcategory = db.SubcategoryModel.Find(subcategoryId);
                    if (subcategory == null)
                        return Json(new { statusCode = 404, success = false, responseMessage = "Not found!" });

                    db.SubcategoryModel.Remove(subcategory);
                    db.SaveChanges();

                    return Json(new { statusCode = 200, success = true, responseMessage = "Category Deleted!" });
                }

                return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
            }
            catch
            {
                return View();
            }
        }
    }
}

WebShop/Views/Subcategory/Admin_Subcategory_Create.cshtml
@model WebShop.Models.SubcategoryModels
@using WebShop.Models

@{
    List<CategoryModels> categories = (List<CategoryModels>)ViewBag.categories;
}

<div id="errorContainer" class="alert alert-danger hidden">

</div>

<div class="form-horizontal">

    <div class="form-group">
        <div class="col-md-12">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Subcategory Name" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <select class="form-control" id="Category">
                @if (categories != null)
                {
                    foreach (var category in categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                }
            </select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Create" class="btn btn-primary" onclick="addNewSubcategory();" />
        </div>
    </div>
</div>

WebShop/Views/Subcategory/Admin_Subcategory_Edit.cshtml
@model WebShop.Models.SubcategoryModels
@using WebShop.Models

@{
    List<CategoryModels> categories = (List<CategoryModels>)ViewBag.categories;
}

<div id="errorContainer" class="alert alert-danger hidden">

</div>

<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-12" style="margin-bottom:5px;">
            <input type="text" id="Name_@Model.Id" name="Name" placeholder="Category Name" class="form-control" value="@Model.Name" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12" style="text-align:left">
            <input type="submit" value="Edit" class="btn btn-primary" onclick="editSubcategory(@Model.Id);" />
        </div>
    </div>
</div>

WebShop/Views/Subcategory/Admin_Subcategory_Index.cshtml
@model IEnumerable<WebShop.Models.SubcategoryModels>

<div class="panel">

    <p class="panel-heading">
        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#addNewSubcategoryModal">Add New</a>
    </p>

    <div style="overflow-x:auto" class="panel-body">
        <table class="table table-striped">
            <thead class="thead-inverse">
                <tr>
                    <th>
                        Category
                    </th>
                    <th>
                        Subcategory
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th>
                            @Html.DisplayFor(modelItem => item.CategoryModels.Name)
                        </th>
                        <th>
                            @Html.DisplayFor(modelItem => item.Name)
                        </th>
                        <th style="position:relative;">
                            <div id="actionButtons">
                                <a href="#" class="editDeleteDetailsButton" data-toggle="modal" data-target="#editSubcategoryModal_@item.Id"><i class="fa fa-edit" style="color:#387738;"></i></a>
                                <a href="#" class="editDeleteDetailsButton" value="button" onclick="deleteSubcategory(@item.Id);"><i class="fa fa-trash" style="color:#c74646;"></i></a>
                            </div>
                            <!-- Category Modal -->
                            <div class="modal fade" id="editSubcategoryModal_@item.Id" tabindex="-1" role="dialog" aria-labelledby="editSubcategory" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h3 class="modal-title text-center">Edit Subcategory</h3>
                                        </div>
                                        <div class="modal-body">
                                            @Html.Action("Admin_Subcategory_Edit", "Subcategory", new { subcategoryId = item.Id })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addNewSubcategoryModal" tabindex="-1" role="dialog" aria-labelledby="addCategory" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-center">Add New Subcategory</h3>
            </div>
            <div class="modal-body">
                @Html.Action("Admin_Subcategory_Create", "Subcategory")
            </div>
        </div>
    </div>
</div>