WebShop/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class CategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Category
        [HttpGet]
        public ActionResult Admin_Category_Index()
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    return PartialView(db.CategoryModel.ToList());

                return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: Category/Create
        [HttpGet]
        public ActionResult Admin_Category_Create()
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    return PartialView();

                return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // POST: Category/Create
        [HttpPost]
        public ActionResult Admin_Category_Create(CategoryModels categoryModel)
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin")) {
                    List<string> allErrors = new List<string>();

                    if (categoryModel.Name == null || categoryModel.Name == String.Empty)
                        allErrors.Add("Name is required!");

                    if (allErrors.Count > 0)
                        return Json(new { statusCode = 400, success = false, responseMessage = allErrors });

                    db.CategoryModel.Add(categoryModel);
                    db.SaveChanges();

                    return Json(new { statusCode = 200, success = true, responseMessage = "Category Added!" });
                }

                return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // GET: Category/Edit/5
        [HttpGet]
        public ActionResult Admin_Category_Edit(int categoryId)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                CategoryModels category = db.CategoryModel.Find(categoryId);

                if (category == null)
                    return Json(new { statusCode = 404, success = false, responseMessage = "Not found!" });

                return PartialView(category);
            }

            return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
        }

        // POST: Category/Edit/5
        [HttpPost]
        public ActionResult Admin_Category_Edit(CategoryModels categoryModel)
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    CategoryModels category = db.CategoryModel.Find(categoryModel.Id);

                    if (category == null)
                        return Json(new { statusCode = 404, success = false, responseMessage = "Not found!" });
                    
                    List<string> allErrors = new List<string>();

                    if (categoryModel.Name == null || categoryModel.Name == String.Empty)
                        allErrors.Add("Name is required!");

                    if (allErrors.Count > 0)
                        return Json(new { statusCode = 400, success = false, responseMessage = allErrors });

                    category.Name = categoryModel.Name;
                    db.SaveChanges();

                    return Json(new { statusCode = 200, success = true, responseMessage = "Category Edited!" });
                }

                return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
            }
            catch (Exception)
            {
                throw;
            }
        }

        // POST: Category/Delete/5
        [HttpPost]
        public ActionResult Admin_Category_Delete(int categoryId)
        {
            try
            {
                if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    CategoryModels category = db.CategoryModel.Find(categoryId);
                    if (category == null)
                        return Json(new { statusCode = 404, success = false, responseMessage = "Not found!" });

                    db.CategoryModel.Remove(category);
                    db.SaveChanges();

                    return Json(new { statusCode = 200, success = true, responseMessage = "Category Deleted!" });
                }

                return Json(new { statusCode = 401, success = false, responseMessage = "Unathorized!" });
            }
            catch
            {
                return View();
            }
        }
    }
}

WebShop/Views/Category/Admin_Category_Create.cshtml
@model WebShop.Models.CategoryModels

<div id="errorContainer" class="alert alert-danger hidden">

</div>

<div class="form-horizontal">

    <div class="form-group">
        <div class="col-md-12">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Category Name" } })
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Create" class="btn btn-primary" onclick="addNewCategory();" />
        </div>
    </div>
</div>

WebShop/Views/Category/Admin_Category_Edit.cshtml
@model WebShop.Models.CategoryModels

<div id="errorContainer" class="alert alert-danger hidden">

</div>

<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-12" style="margin-bottom:5px;">
            <input type="text" id="Name_@Model.Id" name="Name" placeholder="Category Name" class="form-control" value="@Model.Name"/>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12" style="text-align:left">
            <input type="submit" value="Edit" class="btn btn-primary" onclick="editCategory(@Model.Id);" />
        </div>
    </div>
</div>

WebShop/Views/Category/Admin_Category_Index.cshtml
@model IEnumerable<WebShop.Models.CategoryModels>

<div class="panel">

    <p class="panel-heading">
        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#addNewCategoryModal">Add New</a>
    </p>

    <div style="overflow-x:auto" class="panel-body">
        <table class="table table-striped">
            <thead class="thead-inverse">
                <tr>
                    <th>
                        Category
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th>
                            @Html.DisplayFor(modelItem => item.Name)
                        </th>
                        <th style="position:relative;">
                            <div id="actionButtons">
                                <a href="#" class="editDeleteDetailsButton" data-toggle="modal" data-target="#editCategoryModal_@item.Id"><i class="fa fa-edit" style="color:#387738;"></i></a>
                                <a href="#" class="editDeleteDetailsButton" value="button" onclick="deleteCategory(@item.Id);"><i class="fa fa-trash" style="color:#c74646;"></i></a>
                            </div>
                            <!-- Category Modal -->
                            <div class="modal fade" id="editCategoryModal_@item.Id" tabindex="-1" role="dialog" aria-labelledby="editCategory" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h3 class="modal-title text-center">Edit Category</h3>
                                        </div>
                                        <div class="modal-body">
                                            @Html.Action("Admin_Category_Edit", "Category", new { categoryId = item.Id })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addNewCategoryModal" tabindex="-1" role="dialog" aria-labelledby="addCategory" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-center">Add New Category</h3>
            </div>
            <div class="modal-body">
                @Html.Action("Admin_Category_Create", "Category")
            </div>
        </div>
    </div>
</div>